Repository asqw887/Czechgram, pull requests merged in 2022-07, with the labels that each got.

#4 Home 화면 레이아웃 구현
  Czechgram/Czechgram.xcodeproj/project.pbxproj
  Czechgram/Czechgram.xcodeproj/xcshareddata/xcschemes/Czechgram.xcscheme
  Czechgram/Czechgram/Assets.xcassets/userImage.imageset/Contents.json
  Czechgram/Czechgram/Assets.xcassets/userImage.imageset/스크린샷 2022-07-11 오후 4.19.14.png
  Czechgram/Czechgram/HomeCollectionViewDataSource.swift
  Czechgram/Czechgram/HomeNavigationTitleView.swift
  Czechgram/Czechgram/HomeViewController.swift
  Czechgram/Czechgram/PostCell.swift
  Czechgram/Czechgram/ProfileView.swift
  Czechgram/Czechgram/SceneDelegate.swift
Labels: feat

#5 기존 collectionview에 범용적인 datasource 적용하여 리팩토링
  Czechgram/Czechgram.xcodeproj/project.pbxproj
  Czechgram/Czechgram/DetailScene/View/DetailButtonSection.swift
  Czechgram/Czechgram/DetailScene/View/DetailCollectionViewCell.swift
  Czechgram/Czechgram/DetailScene/View/DetailDescriptionSection.swift
  Czechgram/Czechgram/DetailScene/View/DetailProfileSection.swift
  Czechgram/Czechgram/DetailScene/View/DetailView.swift
  Czechgram/Czechgram/DetailScene/View/DetailViewController.swift
  Czechgram/Czechgram/HomeScene/View/HomeCollectionViewDataSource.swift
  Czechgram/Czechgram/HomeScene/View/HomeNavigationTitleView.swift
  Czechgram/Czechgram/HomeScene/View/HomeViewController.swift
  Czechgram/Czechgram/HomeScene/View/PostCell.swift
  Czechgram/Czechgram/HomeScene/View/ProfileView.swift
Labels: refactor

#11 Endpoint 구현
  Czechgram/Czechgram.xcodeproj/project.pbxproj
  Czechgram/Czechgram/Network/Endpoint.swift
  Czechgram/Czechgram/Network/Endpontable.swift
  Czechgram/Czechgram/Network/HTTPMethod.swift
Labels: feat

#14 인스타그램 로그인 기능 구현
  Czechgram/Czechgram.xcodeproj/project.pbxproj
  Czechgram/Czechgram/DataLayer/Network/EndPoint/Endpoint.swift
  Czechgram/Czechgram/DataLayer/Network/EndPoint/HTTPMethod.swift
  Czechgram/Czechgram/DataLayer/Network/EndPoint/Protocol/Endpontable.swift
  Czechgram/Czechgram/DataLayer/Network/Service/NetworkError.swift
  Czechgram/Czechgram/DataLayer/Network/Service/NetworkService.swift
  Czechgram/Czechgram/DataLayer/Network/Service/Protocol/NetworkServiceable.swift
  Czechgram/Czechgram/Helper/Observable.swift
  Czechgram/Czechgram/Info.plist
  Czechgram/Czechgram/LoginScene/ViewModel/LoginViewModel.swift
  Czechgram/Czechgram/Network/EndPoint/Endpoint.swift
  Czechgram/Czechgram/Network/Service/NetworkService.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/CollectionViewDatasource.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailButtonSection.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailCollectionViewCell.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailDescriptionSection.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailProfileSection.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailView.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailViewController.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/HomeNavigationTitleView.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/HomeViewController.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/PostCell.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/ProfileView.swift
  Czechgram/Czechgram/PresentationLayer/LoginScene/View/LoginViewController.swift
  Czechgram/Czechgram/PresentationLayer/LoginScene/ViewModel/LoginViewModel.swift
  Czechgram/Czechgram/SceneDelegate.swift
Labels: feat, refactor

#16 인스타그램 로그인 흐름 패턴화
  Czechgram/Czechgram.xcodeproj/project.pbxproj
  Czechgram/Czechgram/DomainLayer/LoginUsecase/InstagramLoginUsecase.swift
  Czechgram/Czechgram/DomainLayer/LoginUsecase/Protocol/OAuthLoginUsecase.swift
  Czechgram/Czechgram/PresentationLayer/LoginScene/ViewModel/LoginViewModel.swift
Labels: refactor

#21 Home scene 데이터 연결 구현
  Czechgram/Czechgram.xcodeproj/project.pbxproj
  Czechgram/Czechgram/DataLayer/DTO/MediaDTO.swift
  Czechgram/Czechgram/DataLayer/DTO/MediaPagingDTO.swift
  Czechgram/Czechgram/DataLayer/DTO/MediaUrlDTO.swift
  Czechgram/Czechgram/DataLayer/DTO/UserPageDTO.swift
  Czechgram/Czechgram/DataLayer/FileManager/FileCachedService.swift
  Czechgram/Czechgram/DataLayer/FileManager/ImageCacheService.swift
  Czechgram/Czechgram/DataLayer/Network/EndPoint/Endpoint.swift
  Czechgram/Czechgram/DataLayer/Network/Service/NetworkService.swift
  Czechgram/Czechgram/DataLayer/Network/Service/Protocol/NetworkServiceable.swift
  Czechgram/Czechgram/DataLayer/Repository/Protocol/ViewMyPageRepository.swift
  Czechgram/Czechgram/DataLayer/Repository/ViewDefaultMyPageRepository.swift
  Czechgram/Czechgram/DomainLayer/Entity/MediaEntity.swift
  Czechgram/Czechgram/DomainLayer/Entity/MediaImageEntity.swift
  Czechgram/Czechgram/DomainLayer/Entity/UserPageEntity.swift
  Czechgram/Czechgram/DomainLayer/HomeUsecase/Protocol/ViewMyPageUsecase.swift
  Czechgram/Czechgram/DomainLayer/HomeUsecase/ViewDefaultMyPageUsecase.swift
  Czechgram/Czechgram/DomainLayer/LoginUsecase/InstagramLoginUsecase.swift
  Czechgram/Czechgram/Helper/JSONConverter.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/HomeViewController.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/ProfileView.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/ViewModel/HomeViewModel.swift
  Czechgram/Czechgram/PresentationLayer/LoginScene/ViewModel/LoginViewModel.swift
  Czechgram/Czechgram/SceneDelegate.swift
Labels: feat

#23 Detail Scene 데이터 연결
  Czechgram/Czechgram.xcodeproj/project.pbxproj
  Czechgram/Czechgram/DataLayer/DTO/MediaDTO.swift
  Czechgram/Czechgram/DataLayer/Network/EndPoint/Endpoint.swift
  Czechgram/Czechgram/DataLayer/Repository/Protocol/ViewDetailPageRepository.swift
  Czechgram/Czechgram/DataLayer/Repository/Protocol/ViewMainPageRepository.swift
  Czechgram/Czechgram/DataLayer/Repository/ViewDefaultDetailPageRepository.swift
  Czechgram/Czechgram/DataLayer/Repository/ViewDefaultMainPageRepository.swift
  Czechgram/Czechgram/DomainLayer/DetailUsecase/Protocol/ViewDetailPageUsecase.swift
  Czechgram/Czechgram/DomainLayer/DetailUsecase/ViewDefaultDetailPageUsecase.swift
  Czechgram/Czechgram/DomainLayer/HomeUsecase/Protocol/ViewMainPageUsecase.swift
  Czechgram/Czechgram/DomainLayer/HomeUsecase/ViewDefaultMainPageUsecase.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailView.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailViewController.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/ViewModel/DetailViewModel.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/HomeViewController.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/ViewModel/HomeViewModel.swift
Labels: enhancement

#24 Home 화면에서 스크롤을 해 추가 이미지 불러오기
  Czechgram/Czechgram.xcodeproj/project.pbxproj
  Czechgram/Czechgram/Helper/Observable.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/CollectionViewDatasource.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/HomeViewController.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/LoadingReusableView.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/ViewModel/HomeViewModel.swift
Labels: feat, refactor

#25 Rx 적용 전, 기능 구현 완성
  Czechgram/Czechgram.xcodeproj/project.pbxproj
  Czechgram/Czechgram.xcodeproj/xcshareddata/xcschemes/Czechgram.xcscheme
  Czechgram/Czechgram/AppDelegate.swift
  Czechgram/Czechgram/Assets.xcassets/Instagram-Icon.imageset/Contents.json
  Czechgram/Czechgram/Assets.xcassets/Instagram-Icon.imageset/Instagram-Icon.png
  Czechgram/Czechgram/Assets.xcassets/userImage.imageset/Contents.json
  Czechgram/Czechgram/Assets.xcassets/userImage.imageset/스크린샷 2022-07-11 오후 4.19.14.png
  Czechgram/Czechgram/Base.lproj/Main.storyboard
  Czechgram/Czechgram/DataLayer/DTO/MediaDTO.swift
  Czechgram/Czechgram/DataLayer/DTO/MediaPagingDTO.swift
  Czechgram/Czechgram/DataLayer/DTO/MediaUrlDTO.swift
  Czechgram/Czechgram/DataLayer/DTO/UserPageDTO.swift
  Czechgram/Czechgram/DataLayer/FileManager/FileCachedService.swift
  Czechgram/Czechgram/DataLayer/FileManager/ImageCacheService.swift
  Czechgram/Czechgram/DataLayer/Network/EndPoint/Endpoint.swift
  Czechgram/Czechgram/DataLayer/Network/EndPoint/HTTPMethod.swift
  Czechgram/Czechgram/DataLayer/Network/EndPoint/Protocol/Endpontable.swift
  Czechgram/Czechgram/DataLayer/Network/Service/NetworkError.swift
  Czechgram/Czechgram/DataLayer/Network/Service/NetworkService.swift
  Czechgram/Czechgram/DataLayer/Network/Service/Protocol/NetworkServiceable.swift
  Czechgram/Czechgram/DataLayer/Repository/Protocol/ViewDetailPageRepository.swift
  Czechgram/Czechgram/DataLayer/Repository/Protocol/ViewMainPageRepository.swift
  Czechgram/Czechgram/DataLayer/Repository/ViewDefaultDetailPageRepository.swift
  Czechgram/Czechgram/DataLayer/Repository/ViewDefaultMainPageRepository.swift
  Czechgram/Czechgram/DomainLayer/DetailUsecase/Protocol/ViewDetailPageUsecase.swift
  Czechgram/Czechgram/DomainLayer/DetailUsecase/ViewDefaultDetailPageUsecase.swift
  Czechgram/Czechgram/DomainLayer/Entity/MediaEntity.swift
  Czechgram/Czechgram/DomainLayer/Entity/MediaImageEntity.swift
  Czechgram/Czechgram/DomainLayer/Entity/UserPageEntity.swift
  Czechgram/Czechgram/DomainLayer/HomeUsecase/Protocol/ViewMainPageUsecase.swift
  Czechgram/Czechgram/DomainLayer/HomeUsecase/ViewDefaultMainPageUsecase.swift
  Czechgram/Czechgram/DomainLayer/LoginUsecase/InstagramLoginUsecase.swift
  Czechgram/Czechgram/DomainLayer/LoginUsecase/Protocol/OAuthLoginUsecase.swift
  Czechgram/Czechgram/Extension +/UIStackView +.swift
  Czechgram/Czechgram/Extension +/UIView +.swift
  Czechgram/Czechgram/Helper/JSONConverter.swift
  Czechgram/Czechgram/Helper/Observable.swift
  Czechgram/Czechgram/Info.plist
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/CollectionViewDatasource.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailButtonSection.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailCollectionViewCell.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailDescriptionSection.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailProfileSection.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailView.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/View/DetailViewController.swift
  Czechgram/Czechgram/PresentationLayer/DetailScene/ViewModel/DetailViewModel.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/HomeNavigationTitleView.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/HomeViewController.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/LoadingReusableView.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/PostCell.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/View/ProfileView.swift
  Czechgram/Czechgram/PresentationLayer/HomeScene/ViewModel/HomeViewModel.swift
  Czechgram/Czechgram/PresentationLayer/LoginScene/View/LoginViewController.swift
  Czechgram/Czechgram/PresentationLayer/LoginScene/ViewModel/LoginViewModel.swift
  Czechgram/Czechgram/SceneDelegate.swift
  Czechgram/Czechgram/ViewController.swift
Labels: feat
